---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    runtime: nvidia
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
      - ADVERTISE=http://ninjabot:32400
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./config:/config
      - /tmp:/transcode
      - /mnt/bender/storage/tv:/tv
      - /mnt/bender/storage/movies:/movies
    #    devices:
    #      - /dev/dri:/dev/dri
    restart: unless-stopped
